{% set name = "jrsync" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jrsync-{{ version }}.tar.gz
  sha256: 67301ee60ee440310ee229b5071144770c62c486f295a25cd0af14ebf987d173

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - pydantic >=2.8.2,<3.0.0
    - pyyaml >=6.0.1,<7.0.0
    - pytest >=8.3.2,<9.0.0

test:
  imports:
    - jrsync
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/jrsync/
  summary: JSON Configurable wrapper on unix rsync
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anto6715
